version: "3"
services:
  h2_database:
    image: mchurakou/h2_mikalai:1
    ports:
      - "81:81"
      - "1521:1521"

  turbo:
    image: mchurakou/turbo:2
    ports:
      - "8080:8080"
    environment:
      H2_URL: "h2_database"
      H2_PORT: "1521"
      PROFILE: "prod"

    deploy:
      replicas: 2





