logging:
  level:
    root: INFO
    org:
      hibernate:
#        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: Trace

spring:
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        cache:
          use_query_cache: true
          use_second_level_cache: true
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory



management:
  endpoint:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: env
h2:
  console:
    enabled: true

---
spring:
  profiles: test
graph:
  graphPath: input/input.cvs

---
spring:
  profiles: prod
  datasource:
    url: jdbc:h2:tcp://${H2_URL}/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: never

h2:
  console:
    enabled: false
